//! Programmable strategy interface for Clobster.
//!
//! This module provides a flexible framework for implementing custom trading strategies
//! on Polymarket. Strategies can react to market data, generate signals, and manage
//! risk according to user-defined rules.
//!
//! # Architecture
//!
//! - [`Strategy`]: Core trait that all strategies must implement
//! - [`StrategyContext`]: Market data and state provided to strategies
//! - [`Signal`]: Trading signals generated by strategies
//! - [`StrategyEngine`]: Manages strategy lifecycle and execution
//!
//! # Example
//!
//! ```rust,ignore
//! use clobster::strategy::{Strategy, StrategyContext, Signal, StrategyConfig};
//!
//! struct MyStrategy {
//!     threshold: f64,
//! }
//!
//! impl Strategy for MyStrategy {
//!     fn name(&self) -> &str { "my_strategy" }
//!
//!     fn evaluate(&mut self, ctx: &StrategyContext) -> Vec<Signal> {
//!         let mut signals = vec![];
//!         for market in ctx.markets() {
//!             if let Some(outcome) = market.outcomes.first() {
//!                 if outcome.price < self.threshold {
//!                     signals.push(Signal::buy(market.id.clone(), outcome.token_id.clone(), 0.10));
//!                 }
//!             }
//!         }
//!         signals
//!     }
//! }
//! ```

mod context;
mod engine;
mod risk;
mod signal;
mod strategies;
mod traits;

pub use context::{MarketSnapshot, OrderSnapshot, PositionSnapshot, StrategyContext};
pub use engine::{StrategyEngine, StrategyHandle, StrategyStatus};
pub use risk::{RiskConfig, RiskGuard, RiskViolation};
pub use signal::{Signal, SignalStrength, SignalType};
pub use strategies::{MeanReversionStrategy, MomentumStrategy, SpreadStrategy};
pub use traits::{
    ParameterDef, ParameterType, ParameterValue, Strategy, StrategyConfig, StrategyMetadata,
};
